spring.application.name=backend

spring.datasource.url=jdbc:h2:file:./data/gesmin;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB
gesmin.pdf-firmados-dir=./data/pdf-firmados
gesmin.pdf-generados-dir=./data/pdf-generados
